name: Package
on: workflow_dispatch
jobs:
  Package:
    name: pack
    runs-on: ubuntu-latest
    container:
      image: immortalwrt/opde:base
    steps:
      - name: Checkout
        uses: actions/checkout@openwrt-21.02
      - name: pack_install
        run: |
          ./scripts/feeds update -a && ./scripts/feeds install -a
