name: Package
on: workflow_dispatch
jobs:
  Package:
    name: pack
    runs-on: ubuntu-latest
    container:
      image: immortalwrt/opde:base
      options: --user 1001
      env:
        TERM: xterm
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: pack_install
        run: |
          ./scripts/feeds update -a && ./scripts/feeds install -a
          make
